
export type Lang = 'ja' | 'en';

export interface TranslationSchema {
  nav_service: string;
  nav_about: string;
  nav_greeting: string;
  nav_company: string;
  nav_contact: string;
  brand: string;
  hero_title_line1: string;
  hero_title_line2: string;
  about_title: string;
  about_desc: string;
  about_desc_long: string;
  greeting_title: string;
  greeting_name: string;
  greeting_body_long: string;
  service_title: string;
  service_subtitle: string;
  service_note_more: string;
  svc1_title: string;
  svc1_desc: string;
  svc2_title: string;
  svc2_desc: string;
  svc3_title: string;
  svc3_desc: string;
  svc4_title: string;
  svc4_desc: string;
  svc5_title: string;
  svc5_desc: string;
  svc6_title: string;
  svc6_desc: string;
  company_title: string;
  company_name_label: string;
  company_name_value: string;
  company_address_label: string;
  company_address_value: string;
  company_rep_label: string;
  company_rep_value: string;
  company_biz_label: string;
  company_biz_value: string;
  contact_title: string;
  contact_subtitle: string;
  contact_name: string;
  contact_email: string;
  contact_phone: string;
  contact_message: string;
  contact_send: string;
  footer_rights: string;
  footer_copyright: string;
  ai_assistant_title: string;
  ai_assistant_placeholder: string;
  ai_assistant_disclaimer: string;
}
